
class UnsupportedError(Exception):
    pass


class ProveError(Exception):
    pass
